import React from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const PostingGuidelines = () => {
  return (
    <>
    <Navbar />
    <div className="max-w-4xl mx-auto mt-4 p-6 text-gray-800">
      <h1 className="text-3xl font-bold mb-6">📋 Posting Guidelines & Revenue Rules</h1>
      
      <p className="mb-8">
        Welcome to the Peskaya House Listing Program! To keep the platform high-quality, trustworthy, and rewarding for everyone, please follow the rules below when posting a house.
      </p>

      {/* Section: Content Requirements */}
      <Section title="📸 Content Requirements">
        <List items={[
          "Take good quality, landscape (horizontal) photos of the interior of the house.",
          "Record a portrait (vertical) video of the house.",
          "Post the video on TikTok as a Collab/Co-post with Peskaya.",
          "Include the TikTok video URL when submitting your listing."
        ]} />
      </Section>

      {/* Section: Location Accuracy */}
      <Section title="📍 Location Accuracy">
        <List items={[
          "You must be physically at the house location when posting to ensure accurate geolocation.",
          "Tip: Submit the location while on-site, and edit your post later to add videos and other details.",
          "Warning: Large location errors (like wrong towns) will result in refunds and loss of earnings."
        ]} />
      </Section>

      {/* Section: Contact Details */}
      <Section title="📞 Contact Details">
        <List items={[
          "Provide the caretaker’s or landlord’s phone number for each house you post."
        ]} />
      </Section>

      {/* Section: Revenue Share */}
      <Section title="💰 Revenue Share">
        <List items={[
          "You earn 65% of the revenue generated by your listing views.",
          "Peskaya retains 35% to cover platform costs."
        ]} />
      </Section>

      {/* Section: Payout Schedule */}
      <Section title="🗓️ Payout Schedule">
        <List items={[
          "20th of each month: Payment for earnings from the 1st to 15th.",
          "5th of each month: Payment for earnings from the 16th to end of the month.",
          "If the payout date falls on a weekend or public holiday, payment will be made on the next business day."
        ]} />
      </Section>

      {/* Section: Fraud & Accuracy Policy */}
      <Section title="🚫 Fraud & Accuracy Policy">
        <List items={[
          "Fraudulent listings (non-existent houses) will result in immediate account closure and loss of earnings.",
          "Inaccurate listings requiring refunds may reduce your payouts. Always post accurate information!"
        ]} />
      </Section>

      {/* Section: Keeping Listings Fresh */}
      <Section title="🏠 Keeping Listings Fresh">
        <List items={[
          "Mark houses as 'Unavailable' immediately once fully occupied.",
          "Users and the Peskaya team will help update statuses."
        ]} />
      </Section>

      {/* Closing Note */}
      <h2 className="text-2xl font-semibold mt-10 mb-4">🙌 Thank You!</h2>
      <p className="mb-16">
        Your honesty and effort make Peskaya great — and it pays off! Together, we are building the most trusted house listing platform.
      </p>
    </div>

    <Footer />
    </>
  );
};

const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="text-2xl font-semibold mb-4">{title}</h2>
    {children}
  </div>
);

const List = ({ items }) => (
  <ul className="list-disc list-inside space-y-2">
    {items.map((item, index) => (
      <li key={index}>{item}</li>
    ))}
  </ul>
);

export default PostingGuidelines;
